import { Geist } from 'next/font/google'
import "./globals.css";
import Navbar from '@/components/common-parts/Navbar';
import Footer from '@/components/common-parts/Footer';
import CheckInProvider from '@/context/CheckInProvider';
import { Flip, ToastContainer } from 'react-toastify';


const geist = Geist({
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geist.className} h-full antialiased`}
      data-theme="light"
    >
      <body className="min-h-full flex flex-col bg-[#F8FAFC]">
        <Navbar></Navbar>
        <CheckInProvider>
          {children}
        </CheckInProvider>
        <Footer></Footer>

        {/* <ToastContainer position="top-center" /> */}
        <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          transition={Flip}
        />
      </body>
    </html>
  );
}
