import { Geist } from 'next/font/google'
import "./globals.css";
import Navbar from '@/components/common-parts/Navbar/Navbar';
import Footer from '@/components/common-parts/Footer';


const geist = Geist({
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geist.className} h-full antialiased`}
      data-theme="light"
    >
      <body className="min-h-full flex flex-col bg-[#F8FAFC]">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
